### ISSUE TITLE
agenda() does not return entries in API/Appointments

### ISSUE THREAD

**Issue by intco** [SuperSaaS/supersaas-php-api-client#1]
When calling the agenda method of the API\Appointments class the returned array is always empty.

This can be fixed by changing the following:
https://github.com/SuperSaaS/supersaas-php-api-client/blob/65016e0c866bd6c659d9f5eeb2f28dc9b2427b60/src/SuperSaaS/API/Appointments.php#L154-157

with:

```php
        if (isset($res["slots"])) {
            $slot = TRUE;
            $res = $res["slots"];
        } elseif (isset($res['bookings'])) {
            $res = $res['bookings'];
        }
```

**Comment by TertiumQuid** [comment]
Thanks for opening the issue and for snippet! This is indeed a bug, and I've just pushed your fix in the 0.9.2 release

I also updated the examples/appointments.php script to perform the `agenda()` request in order to make integration testing easier.
