### ISSUE TITLE
[feature request] Models\Resource should have more fields

### ISSUE THREAD

**Issue by intco** [SuperSaaS/supersaas-php-api-client#3]
When calling the resources() method of the API\Schedules class would be useful to have more details for each resource.

I have some resources in a multi resource calendar and would be very nice to have also (besides the id and the name of the resource) the duration of the "service" and each resource required.

Thanks

**Comment by Fjan** [comment]
Thanks for the feedback. I've added it to the feature request list and will let you know if it gets selected for implementation. The feature request list is very long and gets prioritised based on the number of requests we receive so realistically it can take a while, but it seems like a useful suggestion.
